from models import Models
from basic.direction import Direction


models_list = {(Direction.RIGHT, 0): Models.FR_1,
               (Direction.RIGHT, 1): Models.FR_2,
               (Direction.RIGHT, 2): Models.FR_3,
               (Direction.RIGHT, 3): Models.FR_4,
               (Direction.RIGHT, 4): Models.FR_5,
               (Direction.RIGHT, 5): Models.FR_6,
               (Direction.RIGHT, 6): Models.FR_7,
               (Direction.RIGHT, 7): Models.FR_8,
               (Direction.RIGHT, 8): Models.FR_9,
               (Direction.RIGHT, 9): Models.FR_10,
               (Direction.RIGHT, 10): Models.FR_11,
               (Direction.RIGHT, 11): Models.FR_12,
               (Direction.RIGHT, 12): Models.FR_13,
               (Direction.RIGHT, 13): Models.FR_14,
               (Direction.RIGHT, 14): Models.FR_15,
               (Direction.RIGHT, 15): Models.FR_16,
               (Direction.RIGHT, 16): Models.FR_17,
               (Direction.RIGHT, 17): Models.FR_18,
               (Direction.RIGHT, 18): Models.FR_19,
               (Direction.RIGHT, 19): Models.FR_20,
               (Direction.RIGHT, 20): Models.FR_21,
               (Direction.RIGHT, 21): Models.FR_22,
               (Direction.LEFT, 0): Models.FL_1,
               (Direction.LEFT, 1): Models.FL_2,
               (Direction.LEFT, 2): Models.FL_3,
               (Direction.LEFT, 3): Models.FL_4,
               (Direction.LEFT, 4): Models.FL_5,
               (Direction.LEFT, 5): Models.FL_6,
               (Direction.LEFT, 6): Models.FL_7,
               (Direction.LEFT, 7): Models.FL_8,
               (Direction.LEFT, 8): Models.FL_9,
               (Direction.LEFT, 9): Models.FL_10,
               (Direction.LEFT, 10): Models.FL_11,
               (Direction.LEFT, 11): Models.FL_12,
               (Direction.LEFT, 12): Models.FL_13,
               (Direction.LEFT, 13): Models.FL_14,
               (Direction.LEFT, 14): Models.FL_15,
               (Direction.LEFT, 15): Models.FL_16,
               (Direction.LEFT, 16): Models.FL_17,
               (Direction.LEFT, 17): Models.FL_18,
               (Direction.LEFT, 18): Models.FL_19,
               (Direction.LEFT, 19): Models.FL_20,
               (Direction.LEFT, 20): Models.FL_21,
               (Direction.LEFT, 21): Models.FL_22}
