from dataclasses import dataclass
from settings_and_data.models_and_sounds import ModelsAndSounds
from basic.direction import Direction


# noinspection DuplicatedCode
@dataclass
class MovingAnimations:
    BARON_MOVING_ANIMATION = {
        (Direction.RIGHT, 0): ModelsAndSounds.R_1,
        (Direction.RIGHT, 1): ModelsAndSounds.R_2,
        (Direction.RIGHT, 2): ModelsAndSounds.R_3,
        (Direction.RIGHT, 3): ModelsAndSounds.R_4,
        (Direction.RIGHT, 4): ModelsAndSounds.R_5,
        (Direction.RIGHT, 5): ModelsAndSounds.R_6,
        (Direction.RIGHT, 6): ModelsAndSounds.R_7,
        (Direction.RIGHT, 7): ModelsAndSounds.R_8,
        (Direction.RIGHT, 8): ModelsAndSounds.R_9,
        (Direction.RIGHT, 9): ModelsAndSounds.R_10,
        (Direction.RIGHT, 10): ModelsAndSounds.R_11,
        (Direction.RIGHT, 11): ModelsAndSounds.R_12,
        (Direction.RIGHT, 12): ModelsAndSounds.R_13,
        (Direction.RIGHT, 13): ModelsAndSounds.R_14,
        (Direction.RIGHT, 14): ModelsAndSounds.R_15,
        (Direction.RIGHT, 15): ModelsAndSounds.R_16,
        (Direction.RIGHT, 16): ModelsAndSounds.R_17,
        (Direction.RIGHT, 17): ModelsAndSounds.R_18,
        (Direction.RIGHT, 18): ModelsAndSounds.R_19,
        (Direction.RIGHT, 19): ModelsAndSounds.R_20,
        (Direction.RIGHT, 20): ModelsAndSounds.R_21,
        (Direction.RIGHT, 21): ModelsAndSounds.R_22,
        (Direction.LEFT, 0): ModelsAndSounds.L_1,
        (Direction.LEFT, 1): ModelsAndSounds.L_2,
        (Direction.LEFT, 2): ModelsAndSounds.L_3,
        (Direction.LEFT, 3): ModelsAndSounds.L_4,
        (Direction.LEFT, 4): ModelsAndSounds.L_5,
        (Direction.LEFT, 5): ModelsAndSounds.L_6,
        (Direction.LEFT, 6): ModelsAndSounds.L_7,
        (Direction.LEFT, 7): ModelsAndSounds.L_8,
        (Direction.LEFT, 8): ModelsAndSounds.L_9,
        (Direction.LEFT, 9): ModelsAndSounds.L_10,
        (Direction.LEFT, 10): ModelsAndSounds.L_11,
        (Direction.LEFT, 11): ModelsAndSounds.L_12,
        (Direction.LEFT, 12): ModelsAndSounds.L_13,
        (Direction.LEFT, 13): ModelsAndSounds.L_14,
        (Direction.LEFT, 14): ModelsAndSounds.L_15,
        (Direction.LEFT, 15): ModelsAndSounds.L_16,
        (Direction.LEFT, 16): ModelsAndSounds.L_17,
        (Direction.LEFT, 17): ModelsAndSounds.L_18,
        (Direction.LEFT, 18): ModelsAndSounds.L_19,
        (Direction.LEFT, 19): ModelsAndSounds.L_20,
        (Direction.LEFT, 20): ModelsAndSounds.L_21,
        (Direction.LEFT, 21): ModelsAndSounds.L_22,
    }

    FOE_MOVING_ANIMATION = {
        (Direction.RIGHT, 0): ModelsAndSounds.FR_1,
        (Direction.RIGHT, 1): ModelsAndSounds.FR_2,
        (Direction.RIGHT, 2): ModelsAndSounds.FR_3,
        (Direction.RIGHT, 3): ModelsAndSounds.FR_4,
        (Direction.RIGHT, 4): ModelsAndSounds.FR_5,
        (Direction.RIGHT, 5): ModelsAndSounds.FR_6,
        (Direction.RIGHT, 6): ModelsAndSounds.FR_7,
        (Direction.RIGHT, 7): ModelsAndSounds.FR_8,
        (Direction.RIGHT, 8): ModelsAndSounds.FR_9,
        (Direction.RIGHT, 9): ModelsAndSounds.FR_10,
        (Direction.RIGHT, 10): ModelsAndSounds.FR_11,
        (Direction.RIGHT, 11): ModelsAndSounds.FR_12,
        (Direction.RIGHT, 12): ModelsAndSounds.FR_13,
        (Direction.RIGHT, 13): ModelsAndSounds.FR_14,
        (Direction.RIGHT, 14): ModelsAndSounds.FR_15,
        (Direction.RIGHT, 15): ModelsAndSounds.FR_16,
        (Direction.RIGHT, 16): ModelsAndSounds.FR_17,
        (Direction.RIGHT, 17): ModelsAndSounds.FR_18,
        (Direction.RIGHT, 18): ModelsAndSounds.FR_19,
        (Direction.RIGHT, 19): ModelsAndSounds.FR_20,
        (Direction.RIGHT, 20): ModelsAndSounds.FR_21,
        (Direction.RIGHT, 21): ModelsAndSounds.FR_22,
        (Direction.LEFT, 0): ModelsAndSounds.FL_1,
        (Direction.LEFT, 1): ModelsAndSounds.FL_2,
        (Direction.LEFT, 2): ModelsAndSounds.FL_3,
        (Direction.LEFT, 3): ModelsAndSounds.FL_4,
        (Direction.LEFT, 4): ModelsAndSounds.FL_5,
        (Direction.LEFT, 5): ModelsAndSounds.FL_6,
        (Direction.LEFT, 6): ModelsAndSounds.FL_7,
        (Direction.LEFT, 7): ModelsAndSounds.FL_8,
        (Direction.LEFT, 8): ModelsAndSounds.FL_9,
        (Direction.LEFT, 9): ModelsAndSounds.FL_10,
        (Direction.LEFT, 10): ModelsAndSounds.FL_11,
        (Direction.LEFT, 11): ModelsAndSounds.FL_12,
        (Direction.LEFT, 12): ModelsAndSounds.FL_13,
        (Direction.LEFT, 13): ModelsAndSounds.FL_14,
        (Direction.LEFT, 14): ModelsAndSounds.FL_15,
        (Direction.LEFT, 15): ModelsAndSounds.FL_16,
        (Direction.LEFT, 16): ModelsAndSounds.FL_17,
        (Direction.LEFT, 17): ModelsAndSounds.FL_18,
        (Direction.LEFT, 18): ModelsAndSounds.FL_19,
        (Direction.LEFT, 19): ModelsAndSounds.FL_20,
        (Direction.LEFT, 20): ModelsAndSounds.FL_21,
        (Direction.LEFT, 21): ModelsAndSounds.FL_22,
    }
