# noinspection PyUnresolvedReferences
from pygame.image import load
from pygame import mixer
from dataclasses import dataclass
from settings_and_data.settings import *


@dataclass
class ModelsAndSounds:
    try:
        BARON_R_IMG = load(IMAGE_PATH + "baron_r.png")
        BARON_L_IMG = load(IMAGE_PATH + "baron_l.png")
        BARON_L_SQUAT_IMG = load(IMAGE_PATH + "baron_l_squat.png")
        BARON_R_SQUAT_IMG = load(IMAGE_PATH + "baron_r_squat.png")
        BARON_R_DAM_IMG = load(IMAGE_PATH + "baron_dam_r.png")
        BARON_L_DAM_IMG = load(IMAGE_PATH + "baron_dam_l.png")
        BARON_L_JUMPING_IMG = load(IMAGE_PATH + "baron_l_jumping.png")
        BARON_R_JUMPING_IMG = load(IMAGE_PATH + "baron_r_jumping.png")
        BARON_L_DAM_JUMPING_IMG = load(IMAGE_PATH + "baron_dam_l_jumping.png")
        BARON_R_DAM_JUMPING_IMG = load(IMAGE_PATH + "baron_dam_r_jumping.png")
        BARON_R_BRAKING_IMG = load(IMAGE_PATH + "baron_r_braking.png")
        BARON_L_BRAKING_IMG = load(IMAGE_PATH + "baron_l_braking.png")
        BARON_R_DAM_BRAKING_IMG = load(IMAGE_PATH + "baron_dam_r_braking.png")
        BARON_L_DAM_BRAKING_IMG = load(IMAGE_PATH + "baron_dam_l_braking.png")

        PLATFORM_IMG = load(IMAGE_PATH + "platform.png")
        BRIDGE_IMG = load(IMAGE_PATH + "bridge.png")
        BRIDGE_DAM = load(IMAGE_PATH + "bridge_dam.png")
        FOE_FLAG_IMG = load(IMAGE_PATH + "foe_flag.png")
        BARON_FLAG_IMG = load(IMAGE_PATH + "baron_flag.png")
        BULLET_IMG = load(IMAGE_PATH + "bullet.png")
        FOE_R_IMG = load(IMAGE_PATH + "foe_r.png")
        FOE_L_IMG = load(IMAGE_PATH + "foe_l.png")
        FOE_R_DAM_IMG = load(IMAGE_PATH + "foe_dam_r.png")
        FOE_L_DAM_IMG = load(IMAGE_PATH + "foe_dam_l.png")
        HEART_IMG = load(IMAGE_PATH + "heart.png")
        TOWER_IMG = load(IMAGE_PATH + "tower.png")
        COMPANION_R = load(IMAGE_PATH + "compan_r.png")
        COMPANION_L = load(IMAGE_PATH + "compan_l.png")
        COMPANION_R_JUMPING = load(IMAGE_PATH + "compan_r_jumping.png")
        COMPANION_L_JUMPING = load(IMAGE_PATH + "compan_l_jumping.png")
        COMPANION_R_DAM = load(IMAGE_PATH + "compan_r_dam.png")
        COMPANION_L_DAM = load(IMAGE_PATH + "compan_l_dam.png")

        R_1 = load(BARON_RIGHT_ANIMATION_PATH + "r_1.png")
        R_2 = load(BARON_RIGHT_ANIMATION_PATH + "r_2.png")
        R_3 = load(BARON_RIGHT_ANIMATION_PATH + "r_3.png")
        R_4 = load(BARON_RIGHT_ANIMATION_PATH + "r_4.png")
        R_5 = load(BARON_RIGHT_ANIMATION_PATH + "r_5.png")
        R_6 = load(BARON_RIGHT_ANIMATION_PATH + "r_6.png")
        R_7 = load(BARON_RIGHT_ANIMATION_PATH + "r_7.png")
        R_8 = load(BARON_RIGHT_ANIMATION_PATH + "r_8.png")
        R_9 = load(BARON_RIGHT_ANIMATION_PATH + "r_9.png")
        R_10 = load(BARON_RIGHT_ANIMATION_PATH + "r_10.png")
        R_11 = load(BARON_RIGHT_ANIMATION_PATH + "r_11.png")
        R_12 = load(BARON_RIGHT_ANIMATION_PATH + "r_12.png")
        R_13 = load(BARON_RIGHT_ANIMATION_PATH + "r_13.png")
        R_14 = load(BARON_RIGHT_ANIMATION_PATH + "r_14.png")
        R_15 = load(BARON_RIGHT_ANIMATION_PATH + "r_15.png")
        R_16 = load(BARON_RIGHT_ANIMATION_PATH + "r_16.png")
        R_17 = load(BARON_RIGHT_ANIMATION_PATH + "r_17.png")
        R_18 = load(BARON_RIGHT_ANIMATION_PATH + "r_18.png")
        R_19 = load(BARON_RIGHT_ANIMATION_PATH + "r_19.png")
        R_20 = load(BARON_RIGHT_ANIMATION_PATH + "r_20.png")
        R_21 = load(BARON_RIGHT_ANIMATION_PATH + "r_21.png")
        R_22 = load(BARON_RIGHT_ANIMATION_PATH + "r_22.png")

        L_1 = load(BARON_LEFT_ANIMATION_PATH + "l_1.png")
        L_2 = load(BARON_LEFT_ANIMATION_PATH + "l_2.png")
        L_3 = load(BARON_LEFT_ANIMATION_PATH + "l_3.png")
        L_4 = load(BARON_LEFT_ANIMATION_PATH + "l_4.png")
        L_5 = load(BARON_LEFT_ANIMATION_PATH + "l_5.png")
        L_6 = load(BARON_LEFT_ANIMATION_PATH + "l_6.png")
        L_7 = load(BARON_LEFT_ANIMATION_PATH + "l_7.png")
        L_8 = load(BARON_LEFT_ANIMATION_PATH + "l_8.png")
        L_9 = load(BARON_LEFT_ANIMATION_PATH + "l_9.png")
        L_10 = load(BARON_LEFT_ANIMATION_PATH + "l_10.png")
        L_11 = load(BARON_LEFT_ANIMATION_PATH + "l_11.png")
        L_12 = load(BARON_LEFT_ANIMATION_PATH + "l_12.png")
        L_13 = load(BARON_LEFT_ANIMATION_PATH + "l_13.png")
        L_14 = load(BARON_LEFT_ANIMATION_PATH + "l_14.png")
        L_15 = load(BARON_LEFT_ANIMATION_PATH + "l_15.png")
        L_16 = load(BARON_LEFT_ANIMATION_PATH + "l_16.png")
        L_17 = load(BARON_LEFT_ANIMATION_PATH + "l_17.png")
        L_18 = load(BARON_LEFT_ANIMATION_PATH + "l_18.png")
        L_19 = load(BARON_LEFT_ANIMATION_PATH + "l_19.png")
        L_20 = load(BARON_LEFT_ANIMATION_PATH + "l_20.png")
        L_21 = load(BARON_LEFT_ANIMATION_PATH + "l_21.png")
        L_22 = load(BARON_LEFT_ANIMATION_PATH + "l_22.png")

        FR_1 = load(FOE_RIGHT_ANIMATION_PATH + "1_r.png")
        FR_2 = load(FOE_RIGHT_ANIMATION_PATH + "2_r.png")
        FR_3 = load(FOE_RIGHT_ANIMATION_PATH + "3_r.png")
        FR_4 = load(FOE_RIGHT_ANIMATION_PATH + "4_r.png")
        FR_5 = load(FOE_RIGHT_ANIMATION_PATH + "5_r.png")
        FR_6 = load(FOE_RIGHT_ANIMATION_PATH + "6_r.png")
        FR_7 = load(FOE_RIGHT_ANIMATION_PATH + "7_r.png")
        FR_8 = load(FOE_RIGHT_ANIMATION_PATH + "8_r.png")
        FR_9 = load(FOE_RIGHT_ANIMATION_PATH + "9_r.png")
        FR_10 = load(FOE_RIGHT_ANIMATION_PATH + "10_r.png")
        FR_11 = load(FOE_RIGHT_ANIMATION_PATH + "11_r.png")
        FR_12 = load(FOE_RIGHT_ANIMATION_PATH + "12_r.png")
        FR_13 = load(FOE_RIGHT_ANIMATION_PATH + "13_r.png")
        FR_14 = load(FOE_RIGHT_ANIMATION_PATH + "14_r.png")
        FR_15 = load(FOE_RIGHT_ANIMATION_PATH + "15_r.png")
        FR_16 = load(FOE_RIGHT_ANIMATION_PATH + "16_r.png")
        FR_17 = load(FOE_RIGHT_ANIMATION_PATH + "17_r.png")
        FR_18 = load(FOE_RIGHT_ANIMATION_PATH + "18_r.png")
        FR_19 = load(FOE_RIGHT_ANIMATION_PATH + "19_r.png")
        FR_20 = load(FOE_RIGHT_ANIMATION_PATH + "20_r.png")
        FR_21 = load(FOE_RIGHT_ANIMATION_PATH + "21_r.png")
        FR_22 = load(FOE_RIGHT_ANIMATION_PATH + "22_r.png")

        FL_1 = load(FOE_LEFT_ANIMATION_PATH + "1_l.png")
        FL_2 = load(FOE_LEFT_ANIMATION_PATH + "2_l.png")
        FL_3 = load(FOE_LEFT_ANIMATION_PATH + "3_l.png")
        FL_4 = load(FOE_LEFT_ANIMATION_PATH + "4_l.png")
        FL_5 = load(FOE_LEFT_ANIMATION_PATH + "5_l.png")
        FL_6 = load(FOE_LEFT_ANIMATION_PATH + "6_l.png")
        FL_7 = load(FOE_LEFT_ANIMATION_PATH + "7_l.png")
        FL_8 = load(FOE_LEFT_ANIMATION_PATH + "8_l.png")
        FL_9 = load(FOE_LEFT_ANIMATION_PATH + "9_l.png")
        FL_10 = load(FOE_LEFT_ANIMATION_PATH + "10_l.png")
        FL_11 = load(FOE_LEFT_ANIMATION_PATH + "11_l.png")
        FL_12 = load(FOE_LEFT_ANIMATION_PATH + "12_l.png")
        FL_13 = load(FOE_LEFT_ANIMATION_PATH + "13_l.png")
        FL_14 = load(FOE_LEFT_ANIMATION_PATH + "14_l.png")
        FL_15 = load(FOE_LEFT_ANIMATION_PATH + "15_l.png")
        FL_16 = load(FOE_LEFT_ANIMATION_PATH + "16_l.png")
        FL_17 = load(FOE_LEFT_ANIMATION_PATH + "17_l.png")
        FL_18 = load(FOE_LEFT_ANIMATION_PATH + "18_l.png")
        FL_19 = load(FOE_LEFT_ANIMATION_PATH + "19_l.png")
        FL_20 = load(FOE_LEFT_ANIMATION_PATH + "20_l.png")
        FL_21 = load(FOE_LEFT_ANIMATION_PATH + "21_l.png")
        FL_22 = load(FOE_LEFT_ANIMATION_PATH + "22_l.png")

        # Title image
        TITLE = load(IMAGE_PATH + "title.png")

        # Sounds
        mixer.init()
        BARON_SHOOT_SOUND = mixer.Sound(SOUND_PATH + "baron_shoot.wav")
        FOE_SHOOT_SOUND = mixer.Sound(SOUND_PATH + "foe.wav")

    except IOError as er:
        print("I/O error in loading models: " + er.strerror)
